import api from './axiosInstance'

export const getClubs = (provincia) => api.get('/clubs', { params: provincia ? { provincia } : {} })
export const getClub = (id) => api.get(`/clubs/${id}`)
export const createClub = (data) => api.post('/clubs', data)
export const updateClub = (id, data) => api.put(`/clubs/${id}`, data)
export const joinClub = (id) => api.post(`/clubs/${id}/join`)
export const leaveClub = (id) => api.delete(`/clubs/${id}/join`)
export const updateMember = (clubId, userId, data) => api.put(`/clubs/${clubId}/members/${userId}`, data)
export const getClubEvents = (clubId) => api.get(`/clubs/${clubId}/events`)
export const createEvent = (clubId, data) => api.post(`/clubs/${clubId}/events`, data)
export const updateEvent = (clubId, eventId, data) => api.put(`/clubs/${clubId}/events/${eventId}`, data)
export const deleteEvent = (clubId, eventId) => api.delete(`/clubs/${clubId}/events/${eventId}`)
export const joinEvent = (clubId, eventId) => api.post(`/clubs/${clubId}/events/${eventId}/join`)
export const leaveEvent = (clubId, eventId) => api.delete(`/clubs/${clubId}/events/${eventId}/join`)
export const getEventParticipants = (clubId, eventId) => api.get(`/clubs/${clubId}/events/${eventId}/participants`)
export const getPublicEvents = () => api.get('/clubs/events/public')
export const getMyClubsEvents = () => api.get('/clubs/events/mine')
export const getClubPosts = (clubId) => api.get(`/clubs/${clubId}/posts`)
export const getRoutes = (clubId) => api.get(`/clubs/${clubId}/routes`)
export const addRoute = (clubId, data) => api.post(`/clubs/${clubId}/routes`, data)
export const updateRoute = (clubId, routeId, data) => api.put(`/clubs/${clubId}/routes/${routeId}`, data)
export const deleteRoute = (clubId, routeId) => api.delete(`/clubs/${clubId}/routes/${routeId}`)
