const router = require('express').Router()
const { getClubs, getClub, createClub, updateClub, joinClub, leaveClub, updateMember, getMyClubes } = require('../controllers/clubsController')
const { getClubEvents, createEvent, updateEvent, deleteEvent, getRoutes, addRoute, updateRoute, deleteRoute, joinEvent, leaveEvent, getEventParticipants, getPublicEvents, getMyClubsEvents } = require('../controllers/eventsController')
const { getClubPosts } = require('../controllers/postsController')
const { requireAuth, optionalAuth } = require('../middleware/auth')
const { upload } = require('../utils/cloudinary')

router.get('/', getClubs)
router.get('/mine', requireAuth, getMyClubes)
router.get('/events/public', optionalAuth, getPublicEvents)
router.get('/events/mine', requireAuth, getMyClubsEvents)
router.get('/:id', getClub)
router.post('/', requireAuth, upload.fields([{ name: 'escudo', maxCount: 1 }, { name: 'portada', maxCount: 1 }]), createClub)
router.put('/:id', requireAuth, upload.fields([{ name: 'escudo', maxCount: 1 }, { name: 'portada', maxCount: 1 }]), updateClub)
router.post('/:id/join', requireAuth, joinClub)
router.delete('/:id/join', requireAuth, leaveClub)
router.put('/:id/members/:userId', requireAuth, updateMember)
router.get('/:clubId/events', optionalAuth, getClubEvents)
router.post('/:clubId/events', requireAuth, createEvent)
router.put('/:clubId/events/:eventId', requireAuth, updateEvent)
router.delete('/:clubId/events/:eventId', requireAuth, deleteEvent)
router.post('/:clubId/events/:eventId/join', requireAuth, joinEvent)
router.delete('/:clubId/events/:eventId/join', requireAuth, leaveEvent)
router.get('/:clubId/events/:eventId/participants', getEventParticipants)
router.get('/:clubId/posts', optionalAuth, getClubPosts)
router.get('/:clubId/routes', getRoutes)
router.post('/:clubId/routes', requireAuth, addRoute)
router.put('/:clubId/routes/:routeId', requireAuth, updateRoute)
router.delete('/:clubId/routes/:routeId', requireAuth, deleteRoute)

module.exports = router
